//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Web_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DapAnDaLuaChon
    {
        public int KetQuaThiID { get; set; }
        public Nullable<int> LanThiID { get; set; }
        public Nullable<int> CauHoiID { get; set; }
        public string DapAnDaChon { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual LanThi LanThi { get; set; }
    }
}
