//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Web_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.LanThis = new HashSet<LanThi>();
            this.CauHois = new HashSet<CauHoi>();
        }
    
        public int DeThiID { get; set; }
        public Nullable<int> MonHocID { get; set; }
        public string TenDeThi { get; set; }
        public Nullable<int> ThoiGianLamBai { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauLamBai { get; set; }
        public string LoaiDe { get; set; }
        public Nullable<int> GiaoVienID { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanThi> LanThis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHoi> CauHois { get; set; }
    }
}
