//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Web_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LanThi()
        {
            this.DapAnDaLuaChons = new HashSet<DapAnDaLuaChon>();
        }
    
        public int LanThiID { get; set; }
        public Nullable<int> HocSinhID { get; set; }
        public Nullable<int> DeThiID { get; set; }
        public Nullable<int> LanThiSo { get; set; }
        public Nullable<double> KetQuaThi { get; set; }
        public Nullable<int> ThoiGianLamBai { get; set; }
        public Nullable<System.DateTime> ThoiGianNopBai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DapAnDaLuaChon> DapAnDaLuaChons { get; set; }
        public virtual DeThi DeThi { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
