//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Web_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int PhanHoiID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> HocSinhID { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
